=== akgbahadarpure1/virtual-classroom/source/WebContent/applet/skin_multilanguage/jcbskin.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- jChatBox client Applet Skin -->
<!ELEMENT JCBSKIN (LOGINPANEL, CHATPANEL)>
<!ATTLIST JCBSKIN
    NAME CDATA #REQUIRED
>
<!ELEMENT LOGINPANEL (LABEL+, BUTTON, TEXTFIELD+, CHOICE)>
<!ATTLIST LOGINPANEL
    FONTNAME CDATA #IMPLIED
    FONTSIZE CDATA #IMPLIED
    FONTSTYLE CDATA #IMPLIED
    BGCOLOR CDATA #IMPLIED
    BGIMAGE CDATA #IMPLIED
>
<!ELEMENT CHATPANEL (LABEL+, BUTTON+, TEXTFIELD, TEXTAREA, LIST)>
<!ATTLIST CHATPANEL
    FONTNAME CDATA #IMPLIED
    FONTSIZE CDATA #IMPLIED
    FONTSTYLE CDATA #IMPLIED
    BGCOLOR CDATA #IMPLIED
    BGIMAGE CDATA #IMPLIED
>
<!ELEMENT LABEL (#PCDATA)>
<!ATTLIST LABEL
    ID CDATA #REQUIRED
    X CDATA #REQUIRED
    Y CDATA #REQUIRED
    WIDTH CDATA #REQUIRED
    HEIGHT CDATA #REQUIRED
    COLOR CDATA #REQUIRED
>
<!ELEMENT BUTTON (#PCDATA)>
<!ATTLIST BUTTON
    ID CDATA #REQUIRED
    X CDATA #REQUIRED
    Y CDATA #REQUIRED
    WIDTH CDATA #REQUIRED
    HEIGHT CDATA #REQUIRED
    COLOR CDATA #REQUIRED
    BGCOLOR CDATA #REQUIRED
>
<!ELEMENT TEXTFIELD EMPTY>
<!ATTLIST TEXTFIELD
    ID CDATA #REQUIRED
    X CDATA #REQUIRED
    Y CDATA #REQUIRED
    WIDTH CDATA #REQUIRED
    HEIGHT CDATA #REQUIRED
    COLOR CDATA #REQUIRED
    BGCOLOR CDATA #REQUIRED
>
<!ELEMENT CHOICE EMPTY>
<!ATTLIST CHOICE
    ID CDATA #REQUIRED
    X CDATA #REQUIRED
    Y CDATA #REQUIRED
    WIDTH CDATA #REQUIRED
    HEIGHT CDATA #REQUIRED
    COLOR CDATA #REQUIRED
    BGCOLOR CDATA #REQUIRED
    FIRSTITEM CDATA #IMPLIED
    TITLE CDATA #IMPLIED
    SEPARATOR CDATA #IMPLIED
>
<!ELEMENT TEXTAREA EMPTY>
<!ATTLIST TEXTAREA
    ID CDATA #REQUIRED
    X CDATA #REQUIRED
    Y CDATA #REQUIRED
    WIDTH CDATA #REQUIRED
    HEIGHT CDATA #REQUIRED
    COLOR CDATA #REQUIRED
    BGCOLOR CDATA #REQUIRED
    JOINMSG CDATA #IMPLIED
    QUITMSG CDATA #IMPLIED
    PRIVATEMSG CDATA #IMPLIED
    ALLMSG CDATA #IMPLIED
>
<!ELEMENT LIST EMPTY>
<!ATTLIST LIST
    ID CDATA #REQUIRED
    X CDATA #REQUIRED
    Y CDATA #REQUIRED
    WIDTH CDATA #REQUIRED
    HEIGHT CDATA #REQUIRED
    COLOR CDATA #REQUIRED
    BGCOLOR CDATA #REQUIRED
    TITLE CDATA #REQUIRED
    SEPARATOR CDATA #REQUIRED
>

=== akgbahadarpure1/virtual-classroom/source/WebContent/applet/skin_manga/jcbskin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- jChatBox client Applet Skin -->
<!DOCTYPE JCBSKIN SYSTEM "jcbskin.dtd">
<JCBSKIN NAME="Manga">
    <LOGINPANEL FONTNAME="Helvetica" FONTSIZE="13" FONTSTYLE="bold" BGCOLOR="000000" BGIMAGE="manga.jpg">
        <LABEL ID="USERNAME" X="7" Y="214" WIDTH="80" HEIGHT="23" COLOR="FFAA55">Username :</LABEL>
        <LABEL ID="CHATROOMS" X="5" Y="113" WIDTH="80" HEIGHT="22" COLOR="FFAA55">Chatrooms :</LABEL>
        <LABEL ID="NAME" X="5" Y="12" WIDTH="220" HEIGHT="22" COLOR="CCDDFF">Chatroom : </LABEL>
        <LABEL ID="DATE" X="13" Y="33" WIDTH="220" HEIGHT="22" COLOR="CCDDFF">Opening : </LABEL>
        <LABEL ID="SUBJECT" X="18" Y="55" WIDTH="220" HEIGHT="22" COLOR="CCDDFF">Subject : </LABEL>
        <LABEL ID="ERROR" X="80" Y="240" WIDTH="267" HEIGHT="22" COLOR="FF5511"/>
        <LABEL ID="WELCOME" X="240" Y="300" WIDTH="250" HEIGHT="51" COLOR="EEEEFF">- Welcome to jChatBox client Applet -|Homepage : http://www.javazoom.net</LABEL>
        <BUTTON ID="LOGIN" X="210" Y="216" WIDTH="68" HEIGHT="22" COLOR="0022AA" BGCOLOR="CCDDFF">Login</BUTTON>
        <TEXTFIELD ID="USERNAME" X="85" Y="216" WIDTH="120" HEIGHT="22" COLOR="0022AA" BGCOLOR="CCDDFF"/>
        <CHOICE ID="ROOMS" X="90" Y="113" WIDTH="140" HEIGHT="22" COLOR="0022AA" BGCOLOR="CCDDFF" FIRSTITEM="Select one NOW !"/>
    </LOGINPANEL>
    <CHATPANEL FONTNAME="Helvetica" FONTSIZE="13" FONTSTYLE="bold" BGCOLOR="000000" BGIMAGE="manga.jpg">
        <LABEL ID="MESSAGE" X="4" Y="4" WIDTH="63" HEIGHT="22" COLOR="FFFFFF">Message :</LABEL>
        <LABEL ID="NAME" X="4" Y="26" WIDTH="190" HEIGHT="22" COLOR="CCCCCC">Chatroom : </LABEL>
        <BUTTON ID="SEND" X="359" Y="4" WIDTH="68" HEIGHT="22" COLOR="002200" BGCOLOR="CCDDFF">Say</BUTTON>
        <BUTTON ID="REFRESH" X="431" Y="4" WIDTH="70" HEIGHT="22" COLOR="222222" BGCOLOR="AABBDD">Refresh</BUTTON>
        <BUTTON ID="LOGOUT" X="431" Y="30" WIDTH="70" HEIGHT="22" COLOR="770000" BGCOLOR="DDBBAA">Quit</BUTTON>
        <TEXTFIELD ID="MESSAGE" X="70" Y="4" WIDTH="280" HEIGHT="22" COLOR="0022DD" BGCOLOR="CCDDFF"/>
        <TEXTAREA ID="MESSAGES" X="10" Y="50" WIDTH="364" HEIGHT="324" COLOR="0022AA" BGCOLOR="CCDDFF" JOINMSG=" has joined the chatroom." QUITMSG=" has left the chatroom." PRIVATEMSG="Next messages are sent to : " ALLMSG="Next messages are sent to ALL chatroom users."/>
        <LIST ID="USERS" X="400" Y="96" WIDTH="100" HEIGHT="245" COLOR="000066" BGCOLOR="CCDDFF" TITLE="> ALL USERS" SEPARATOR="~~~~~~~~~~~"/>
    </CHATPANEL>
</JCBSKIN>

=== akgbahadarpure1/virtual-classroom/source/WebContent/applet/skin_multilanguage/jcbskin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- jChatBox client Applet Skin -->
<!DOCTYPE JCBSKIN SYSTEM "jcbskin.dtd">
<JCBSKIN NAME="MultiLanguages">
    <LOGINPANEL FONTNAME="Helvetica" FONTSIZE="12" FONTSTYLE="bold" BGCOLOR="3366AA">
        <LABEL ID="USERNAME" X="7" Y="14" WIDTH="85" HEIGHT="23" COLOR="FFFFFF">multilanguage</LABEL>
        <LABEL ID="CHATROOMS" X="5" Y="86" WIDTH="117" HEIGHT="22" COLOR="FFFFFF">multilanguage</LABEL>
        <LABEL ID="NAME" X="292" Y="12" WIDTH="190" HEIGHT="22" COLOR="FFFFCC">multilanguage</LABEL>
        <LABEL ID="DATE" X="292" Y="34" WIDTH="206" HEIGHT="22" COLOR="FFFFCC">multilanguage</LABEL>
        <LABEL ID="SUBJECT" X="292" Y="55" WIDTH="190" HEIGHT="22" COLOR="FFFFCC">multilanguage</LABEL>
        <LABEL ID="ERROR" X="5" Y="42" WIDTH="267" HEIGHT="22" COLOR="FF0000"/>
        <LABEL ID="WELCOME" X="344" Y="290" WIDTH="228" HEIGHT="51" COLOR="000022">http://www.javazoom.net</LABEL>
        <BUTTON ID="LOGIN" X="218" Y="16" WIDTH="68" HEIGHT="21" COLOR="000022" BGCOLOR="CCCCFF">multilanguage</BUTTON>
        <TEXTFIELD ID="USERNAME" X="94" Y="16" WIDTH="117" HEIGHT="20" COLOR="000055" BGCOLOR="9999FF"/>
        <CHOICE ID="ROOMS" X="130" Y="87" WIDTH="160" HEIGHT="20" COLOR="000055" BGCOLOR="99AAFF" FIRSTITEM="multilanguage"/>
    </LOGINPANEL>
    <CHATPANEL FONTNAME="Helvetica" FONTSIZE="12" FONTSTYLE="bold" BGCOLOR="3366AA">
        <LABEL ID="MESSAGE" X="4" Y="268" WIDTH="63" HEIGHT="22" COLOR="FFFFFF">multilanguage</LABEL>
        <LABEL ID="NAME" X="4" Y="295" WIDTH="190" HEIGHT="22" COLOR="CCCCFF">multilanguage</LABEL>
        <BUTTON ID="SEND" X="324" Y="270" WIDTH="68" HEIGHT="21" COLOR="000022" BGCOLOR="CCCCFF">multilanguage</BUTTON>
        <BUTTON ID="REFRESH" X="396" Y="270" WIDTH="82" HEIGHT="21" COLOR="222222" BGCOLOR="CCCCDD">multilanguage</BUTTON>
        <BUTTON ID="LOGOUT" X="396" Y="294" WIDTH="70" HEIGHT="21" COLOR="660000" BGCOLOR="CCCCDD">multilanguage</BUTTON>
        <TEXTFIELD ID="MESSAGE" X="65" Y="270" WIDTH="250" HEIGHT="21" COLOR="000055" BGCOLOR="9999FF"/>
        <TEXTAREA ID="MESSAGES" X="10" Y="13" WIDTH="368" HEIGHT="245" COLOR="000033" BGCOLOR="DDDDFF" JOINMSG="multilanguage" QUITMSG="multilanguage" PRIVATEMSG="multilanguage" ALLMSG="multilanguage"/>
        <LIST ID="USERS" X="390" Y="13" WIDTH="100" HEIGHT="245" COLOR="000066" BGCOLOR="CCCCFF" TITLE="multilanguage" SEPARATOR="==========="/>
    </CHATPANEL>
</JCBSKIN>

=== akgbahadarpure1/virtual-classroom/WebContent/applet/skin_comics/jcbskin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- jChatBox client Applet Skin -->
<!DOCTYPE JCBSKIN SYSTEM "jcbskin.dtd">
<JCBSKIN NAME="Comics">
    <LOGINPANEL FONTNAME="Helvetica" FONTSIZE="12" FONTSTYLE="bold" BGCOLOR="000000" BGIMAGE="comics.jpg">
        <LABEL ID="USERNAME" X="26" Y="200" WIDTH="70" HEIGHT="23" COLOR="FF8855">Username :</LABEL>
        <LABEL ID="CHATROOMS" X="5" Y="230" WIDTH="90" HEIGHT="22" COLOR="FF8855">Comics rooms :</LABEL>
        <LABEL ID="NAME" X="280" Y="15" WIDTH="210" HEIGHT="22" COLOR="FFFFFF">Room : </LABEL>
        <LABEL ID="DATE" X="280" Y="50" WIDTH="210" HEIGHT="22" COLOR="DDDDDD">Opened since : </LABEL>
        <LABEL ID="SUBJECT" X="280" Y="32" WIDTH="210" HEIGHT="22" COLOR="EEEEEE">Topic : </LABEL>
        <LABEL ID="ERROR" X="100" Y="289" WIDTH="267" HEIGHT="22" COLOR="FF0000"/>
        <LABEL ID="WELCOME" X="55" Y="352" WIDTH="228" HEIGHT="51" COLOR="FFFFFF">- Welcome to jChatBox client Applet -|Homepage : http://www.javazoom.net</LABEL>
        <BUTTON ID="LOGIN" X="100" Y="266" WIDTH="68" HEIGHT="20" COLOR="FF8855" BGCOLOR="551111">Join</BUTTON>
        <TEXTFIELD ID="USERNAME" X="101" Y="200" WIDTH="120" HEIGHT="21" COLOR="CCDDFF" BGCOLOR="222222"/>
        <CHOICE ID="ROOMS" X="100" Y="230" WIDTH="130" HEIGHT="18" COLOR="DDEEFF" BGCOLOR="222222" FIRSTITEM="Select one ..."/>
    </LOGINPANEL>
    <CHATPANEL FONTNAME="Helvetica" FONTSIZE="12" FONTSTYLE="bold" BGCOLOR="CCDDFF" BGIMAGE="comics.jpg">
        <LABEL ID="MESSAGE" X="4" Y="370" WIDTH="70" HEIGHT="22" COLOR="DDEEFF">Message :</LABEL>
        <LABEL ID="NAME" X="4" Y="392" WIDTH="190" HEIGHT="22" COLOR="DDEEFF">Chatroom : </LABEL>
        <BUTTON ID="SEND" X="415" Y="370" WIDTH="70" HEIGHT="21" COLOR="FF8855" BGCOLOR="551111">Post</BUTTON>
        <BUTTON ID="REFRESH" X="415" Y="346" WIDTH="70" HEIGHT="21" COLOR="222222" BGCOLOR="CCCCCC">Refresh</BUTTON>
        <BUTTON ID="LOGOUT" X="415" Y="12" WIDTH="70" HEIGHT="25" COLOR="220000" BGCOLOR="CCBB55">Logout</BUTTON>
        <TEXTFIELD ID="MESSAGE" X="65" Y="370" WIDTH="320" HEIGHT="21" COLOR="FF8855" BGCOLOR="222222"/>
        <TEXTAREA ID="MESSAGES" X="8" Y="11" WIDTH="368" HEIGHT="350" COLOR="FFFFFF" BGCOLOR="001122" JOINMSG=" has joined the chatroom." QUITMSG=" has left the chatroom." PRIVATEMSG="Next messages are sent to : " ALLMSG="Next messages are sent to ALL chatroom users."/>
        <LIST ID="USERS" X="402" Y="100" WIDTH="100" HEIGHT="240" COLOR="DDEEFF" BGCOLOR="001122" TITLE="> ALL USERS" SEPARATOR="==========="/>
    </CHATPANEL>
</JCBSKIN>
